apiVersion: batch/v1
kind: CronJob
metadata:
  name: turtles-cronjob
spec:
  # 12:30 daily (AWST -> UTC)
  schedule: "30 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: turtles-cronjob
            args: ["manage.py", "automated_qa_checks"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: turtles-env-uat
                  key: DATABASE_URL
