# Generated by Django 4.2.14 on 2024-08-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_organisation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_agreed_to_terms',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has agreed to the terms and conditions.', verbose_name='Has Agreed to Terms'),
        ),
    ]
