apiVersion: batch/v1
kind: CronJob
metadata:
  name: turtles-cronjob
spec:
  # 23:00 daily (AWST -> UTC)
  schedule: "0 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: turtles-cronjob
            args: ["manage.py", "reconstruct_missing_surveys"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: turtles-env-uat
                  key: DATABASE_URL
