# Generated by Django 4.2.14 on 2024-08-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wamtram2', '0005_create_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=50)),
                ('place_code', models.CharField(max_length=50)),
                ('species_code', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='trtobservations',
            options={'managed': False, 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='trtpittags',
            options={'managed': False, 'ordering': ['pittag_id'], 'verbose_name': 'Pit tag', 'verbose_name_plural': 'Pit tags'},
        ),
        migrations.AlterModelOptions(
            name='trttags',
            options={'managed': False, 'ordering': ['tag_id'], 'verbose_name': 'Flipper tag', 'verbose_name_plural': 'Flipper tags'},
        ),
        migrations.AlterModelOptions(
            name='trtturtles',
            options={'managed': False, 'ordering': ['turtle_id'], 'verbose_name': 'Turtle', 'verbose_name_plural': 'Turtles'},
        ),
    ]
