# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1-browsers
        environment:
          # Not using pipenv, but virtualenvwrapper / virtualenv
          - PIPENV_VENV_IN_PROJECT: true
          - DATABASE_URL: postgis://ubuntu@localhost/circle_test?sslmode=disable

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # User MUST be called `ubuntu`
      - image: mdillon/postgis:9.6
        environment:
          POSTGRES_USER: ubuntu
          PGUSER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD:

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Fix file ownership and create log and staticfiles folders
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
            mkdir -p logs staticfiles
            touch logs/wastd.log

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements/dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Install system packages for GDAL
          command: |
            sudo apt-get update
            sudo apt-get install -qq binutils libproj-dev gdal-bin

      - run:
          name: Install Python module dependencies
          command: |
            sudo pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements/dev.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            fab test
          # python manage.py test --settings=config.settings.test --keepdb -v 2

      - store_artifacts:
          path: logs
          destination: test-reports